### ISSUE TITLE
North American version

### ISSUE THREAD

**Issue by VirTERM** [mirakonta/lora_gateway#1]
I am trying to use North American version of Multitech module. Where do I find the correct global_conf.json file?

**Comment by nestorayuso** [comment]
I really don't know. US band is very big, to cover all the band in the specificacion you need a gateway with 8x SX1301. 

With a Multitech gateway, only 1 of 8 sub band is possible. What frequencies or bands are using your nodes?

http://www.multitech.net/developer
http://www.multitech.net/developer/forums/
http://lora.multitech.com/
http://git.multitech.net/cgi-bin/cgit.cgi/lora_gateway.git/tree/util_pkt_logger/cfg/global_conf.us915.json

**Comment by VirTERM** [comment]
I see what you mean. At this point, I am only experimenting so I can use any sub-band. Thank You
