### ISSUE TITLE
 Heat and power dissipated.

### ISSUE THREAD

**Issue by dubanoze** [mirakonta/lora_gateway#2]
In WIKI page you write - And that's all! No more hardware modifications are needed although later I will discuss some improvements to lower the heat and power dissipated.

Please, add this information.
Now I test mCard-LoRa, and is very hot.

Thank you.

**Comment by yseraf** [comment]
which place exactly is very hot ?

**Comment by dubanoze** [comment]
I touch shield. i Don't know  temperature, but very hot. May be is normal?

**Comment by yseraf** [comment]
I just received mine and it seems that the hot part is the 1.8V regulator. If this regulator is powered by the 5V, the only solution is to reduce this voltage to 3.52V (3.3 + the dropout) then the power dissipated will be lower

**Comment by dubanoze** [comment]
What do you think, how we can do it ?

**Comment by yseraf** [comment]
Firstly, is it a problem for you ? 
May be the 2 pins where we put the 5V are not both for the 3.3V regulators, may be one is for the 3.3V (so we have to put at least 3.52V) and the second one is for the 1.8V regultator (then we have to put 1.8V + something) but I don't have ohmmeter to verify that. 
The second possibility is that this is just the normal behavior and we have nothing to do.

If you want to invesigate and you have ohmmeter, I can help you but in all cases, you have to create other voltage, this is not just buying some module on AliExpress and solder a wire, let me know

**Comment by dubanoze** [comment]
i have problem with card. Not all packet delivered from/to card.
How i check it.
I sent packets from one sx1276. another sx1276 receive 100% packet, but mCard 50/50%.
Same on tx from mCard.
I used to think it is due to overheating.

Today i receive iC880A-SPI – LoRaWAN Concentrator 868MHz. Will try connect to RPi.

**Comment by yseraf** [comment]
Yes, I'm at the beginning of my tests but it's true that visibly I don't have all packet received too. I'm also waiting on the iC880A-SPI. 
What I can see now is it works for 5 minutes then no packets anymore.

**Comment by dubanoze** [comment]
What do you mean? mCard work normal 5 minutes ? After no 100 % packets ?

**Comment by yseraf** [comment]
So I just made a test now. Yes, after 5minutes, I didn't get anything but the strange thing was I had to restart the gateway application and then it was ok for 5 more minutes.
My second attempt was to set the TX power to -7dBm and then no problem anymore. 
What I just did is to set the power to 0dBm but with adding a second power supply for the 5V because I have heard often that the multitech module is consuming a lot and the raspberry pi can have problem. 
It's now running, I got 24 packets on 27 every 20seconds so it's seems this is a power problem. 
Which power source are you using ?

**Comment by dubanoze** [comment]
I use DC-DC Boost Adjustable Power 5V 5A directly soldered to RPI pins.
In /boot/config.txt i set max_usb_current=1 for change limit to 1.2 Amp.
24 from 27 packets i think is not good.
Please, share all your experience.

**Comment by yseraf** [comment]
Where the 5V is soldered ? 
I have the normal USB connected and in addition a second 5V USB charger connected to the GPIO extender. 
I added the max_usb_current=1 in /boot/config.txt and now received 70/70 packets

**Comment by dubanoze** [comment]
5V soldered to GPIO 2, 4 pin & GND to ground  near USB port.

**Comment by yseraf** [comment]
Ok so the différences are I'm using pin 2 and 6 and I have removed the shield on the multitech module allowing the heat to drain. I'm also using the binary given by Loriot and the radio config is:

RADIO: radio 0 enabled, SX1257, center frequency 868200000, RSSI offset -166.0, TX enabled
RADIO: radio 1 enabled, SX1257, center frequency 869200000, RSSI offset -166.0, TX disabled
 INFO: LoRa Multi-SF channel 0 >> Radio 0, IF -100000 Hz, 125 kHz BW Enabled
 INFO: LoRa Multi-SF channel 1 >> Radio 0, IF 100000 Hz, 125 kHz BW Enabled
 INFO: LoRa Multi-SF channel 2 >> Radio 0, IF 300000 Hz, 125 kHz BW Enabled
 INFO: LoRa Multi-SF channel 3 >> Radio 1, IF -350000 Hz, 125 kHz BW Enabled
 INFO: LoRa Multi-SF channel 4 >> Radio 1, IF -150000 Hz, 125 kHz BW Enabled
 INFO: LoRa Multi-SF channel 5 >> Radio 1, IF 325000 Hz, 125 kHz BW Enabled
 INFO: no configuration for Lora multi-SF channel 6
 INFO: no configuration for Lora multi-SF channel 7
 INFO: Lora std channel> radio 0, IF 100000 Hz, 250000 Hz bw, SF 7
 INFO: FSK channel> radio 0, IF 100000 Hz, 250000 Hz bw, 50000 bps datarate
 INFO: TX Output Power on all channels adjusted by 0 dBm

**Comment by jegb** [comment]
would you recommend to power the 2 pins on the mcard adapter with 3.5v with a DC-DC converter?
if not, would make sense to get external DC5V 1A power supply, keeping the common ground with the RPI?

**Comment by pete-h** [comment]
Do you guys have an update on the power issue?
I also have an mcard and a RPi and getting ready to play a bit...
So you used a good USB supply and added the set max_usb_current=1 to get 1.2A over USB and also added a second 5V supply to Pins 2 and 6 on the RPi GPIO header, correct?

Did you get the heat problem under control? Heatsink maybe?

Thanks.

**Comment by jegb** [comment]
Regarding thermal creep:
-we have created a case for the mcard module, which includes a fan addressed at the shield, with some vent entry on the sides. Maybe we can upload to thingiverse for convenience.

**Comment by nestorayuso** [comment]
The heat is not a problem at all.
The temperature is not higher than using it in a Conduit

**Comment by pete-h** [comment]
Thanks for the feedback :)

And about the power? Is 1.2A enough for the mcard or is a higher current needed?

**Comment by nestorayuso** [comment]
1A is enough for raspberry-pi + mcard + 3g-dongle but I recommend 2A or more.

**Comment by lassevestergaard** [comment]
Hi guys.

I have the same setup, but I have recently acquired a Raspberry pi 3, which should be able to deliver enough amp directly at the USB port. The issue is that I still get the same problem with 100% CRC_FAIL. I have not yet connected 5V directly to GPIO 2 and 6. It seems a little odd to me, that you need to connect two power supplies to one raspberry pi, and it also seems that it can be a little dangerous since there is no power protection on the GPIOs. Have any of you found new workarounds or tested with a Raspberry 3?

**Comment by lassevestergaard** [comment]
Just an update after some further testing.

I managed to use an old Raspberry pi 1 connecting only an external 5V power supply to GPIO 2 and 6 (meaning no power cable to the micro usb port). This seems to have helped significantly on the CRC_FAIL issue. It is not 100% perfect, but 8 out of 10 messages comes out with CRC_OK: 100.00%

To be completely blunt, this specific setup might be outdated compared to other tutorials popping up all over the internet. The setup is probably good enough for some very simple testing, but looking at the price tag of the multitech lora module alone, it would make sense to use a little extra money on a gateway that is more robust.
