### ISSUE TITLE
Increased LUT table size causes errors

### ISSUE THREAD

**Issue by tpwrules** [mirakonta/lora_gateway#4]
The TX LUT size of 36 causes a failure of AGC initialization. It seems to me the issue is on line 1093 of libloragw/src/loragw_hal.c . The FW is expecting 16 entries but 36 are sent and thus initialization fails.

**Comment by nestorayuso** [comment]
yes, i get the error but hadn't time to fix it or get back

**Comment by nestorayuso** [comment]
fixed with your advice @tpwrules
