### ISSUE TITLE
Dinamically change iface managed by pkt_fwd

### ISSUE THREAD

**Issue by ghost** [mirakonta/lora_gateway#8]
Hi @nestorayuso !

We are testing the packages with `wiki` [here](https://github.com/mirakonta/lora_gateway/wiki) and it is an awesome job and working!

In our case we are using an eth0 (wired cable) interface as default. But also we had configured a ppp0 (modem 3G) interface as second default (backup). 

We know that `pkt_fwd` establishes a connection with the **LoRAWAN Network Server** choosing the default routing interface: `eth0` or `ppp0`.

Our best option is `eth0` iface. The `ppp0` is for a backup connection. 

But since `pkt_fwd` is connected over eth0 and suddenly this interface gets down, the default iface will be `ppp0`. 

At this point, the script must to be `reload` to establishes a connection with the **LoRaWAN Network Server** over `ppp0`.

However we would like the `pkt_fwd` manage this connection without have to `reload` the script as we are doing now. 

Is it possible to include this on `pkt_fwd` script, please?

Best Regards,

Rogério

**Comment by nestorayuso** [comment]
this issue is out of scope of this project
