### ISSUE TITLE
missing GPS device tty in global_conf.json

### ISSUE THREAD

**Issue by Theoi-Meteoroi** [mirakonta/lora_gateway#9]
I put one of these together but could not get the GPS working until I added the section below to the global_conf.json.  Works fine with GPS lock.

        /* GPS configuration */
        "gps_tty_path": "/dev/ttyAMA0",
        /* GPS reference coordinates */
        "ref_latitude": 0.0,
        "ref_longitude": 0.0,
        "ref_altitude": 0

**Comment by nestorayuso** [comment]
done
